### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by anusha7530** [OpenTekHub/blockchain#1]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Girlscript-WOB/Guidelines/blob/main/Project%20Admins/Code%20of%20conduct.md

**Comment by KiranBaliga** [comment]
Can you please assign this issue to me as a part of GSWOB'24?

**Comment by KiranBaliga** [comment]
Please let me know the communication email ID to be included to the code of conduct as a part of reporting point of contact for the project.

**Comment by Harish-2003** [comment]
peddinaharish2003@gmail.com

**Comment by KiranBaliga** [comment]
I have raised a PR. Please review and share the feedback which is highly appreciated. Thank you!

**Comment by Harish-2003** [comment]
Please reference the issue in the pull request
