### ISSUE TITLE
More crypto currencies

### ISSUE THREAD

**Issue by Harish-2003** [OpenTekHub/blockchain#10]
For every crypto currencies level1 is assigned 
For 2 level2 is assigned 
For 3 or more level3 will be assigned

**Comment by IshuSinghSE** [comment]
Hello! Can I be assigned to this?, How many crypto currencies do I have to add?

**Comment by Harish-2003** [comment]
> Hello! Can I be assigned to this?, How many crypto currencies do I have to add?
> 

As many as you want 
Based upon the number of additions the level will be added

**Comment by IshuSinghSE** [comment]
Pls assign it to me, I'll be happy to contribute.

**Comment by IshuSinghSE** [comment]
please could you add a milestone to my PR, because its not showing in issues as other PR

**Comment by IshuSinghSE** [comment]
please close this issue, As the PR for the issue is already merged.
