### ISSUE TITLE
[Feature Request]: Aligning the Crypto Price Predictor in center

### ISSUE THREAD

**Issue by Ashish-Patnaik** [OpenTekHub/blockchain#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Crypto Price Predictor is in right side making the UI looks bad so i need to fix and make a beautiful UI

### Use Case

The Crypto Price Predictor took the center attention and with Better UI it looks beautiful 

### Benefits

UI looks more clean and the header looks attractive

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by 56rahul** [comment]
Kindly assign this issue to me; I would like to contribute to this project.
