### ISSUE TITLE
Need buttons for cryptos

### ISSUE THREAD

**Issue by Harish-2003** [OpenTekHub/blockchain#22]

**Comment by Tomkndn** [comment]
Can you please describe more

**Comment by Harish-2003** [comment]
Presently if u look into the website you need to type the crypto currencies like bth or eth etc I request some buttons or an drop down menu so that while clicking the people can able to see the prices of the crypto currencies

**Comment by Tomkndn** [comment]
so basically now only 2 currencies are there so we want a dropdown where these 2 options can be choosen by the user.
right?

**Comment by Harish-2003** [comment]
Yep

**Comment by Tomkndn** [comment]
So basically i will change the input to dropdown where it will show the currency options which is mentioned in the script.js cryptoMap variable
if this is okay then kindly assign this task to me.

**Comment by Harish-2003** [comment]
Yep but there are currently 3 crypto currencies I guess please look into it and make the suggested changes

**Comment by Tomkndn** [comment]
which 3 can you please mention?

**Comment by Tomkndn** [comment]
all the currencies which is present in the script.js file all values can be predicted I manually tested it.

**Comment by Harish-2003** [comment]
I am so sorry there are more than 3 crypto currencies the drop down menu should also include an search bar

**Comment by Tomkndn** [comment]
yeah sure.

**Comment by Tomkndn** [comment]
is this okay?
![image](https://github.com/user-attachments/assets/ac57c18e-ce51-468c-b93b-4fe91f569b3e)

**Comment by Harish-2003** [comment]
Okay but TRY to mention names along with symbols in the drop down ex-Bitcoin(BTH)

**Comment by Tomkndn** [comment]
For this i have to change the mapping name in the array present in the script.js file
Should i do it?

**Comment by Harish-2003** [comment]
> For this i have to change the mapping name in the array present in the script.js file
> Should i do it?

I don't think you need to, can u send the screenshot of the drop down code

**Comment by Tomkndn** [comment]
This is a code i have added in script.js
![IMG_20240929_231232_571](https://github.com/user-attachments/assets/90d60580-2d2d-4436-9c04-1d6647b985a9)

**Comment by Harish-2003** [comment]
> This is a code i have added in script.js
> ![IMG_20240929_231232_571](https://github.com/user-attachments/assets/90d60580-2d2d-4436-9c04-1d6647b985a9)
> 
Try to make different commits for the different changes and make an pr

**Comment by Tomkndn** [comment]
Should i open a pr now then?
