### ISSUE TITLE
Add detail instruction for Contribution guidelines

### ISSUE THREAD

**Issue by IshuSinghSE** [OpenTekHub/blockchain#27]
I feel that the current instructions in the Contribution Guidelines are not easy to understand for contributors,
who are new to **Git** or **GitHub**. Therefore, I am planning to add more detailed but easy-to-understand _Contribution Guidelines_.

If you feel its needed and want me to work on it, 
Please assign it to me, and add required label.

**Comment by Apeksha-22** [comment]
Please assign me this task, I want to explore and work on it.

**Comment by Muskan-bhatt249** [comment]
@IshuSinghSE Please assign it to me

**Comment by Muskan-bhatt249** [comment]
@IshuSinghSE Please assign this to me I have previous experience of content writing and documentation.

**Comment by J-B-Mugundh** [comment]
@IshuSinghSE @Harish-2003 Improved contribution guidelines. Please check!

https://github.com/OpenTekHub/blockchain/pull/34/commits

**Comment by IshuSinghSE** [comment]
It's has been added
