### ISSUE TITLE
Bug: currently this website doesn't work perfectly in mobile view

### ISSUE THREAD

**Issue by Harish-2003** [OpenTekHub/blockchain#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While opening the website in mobile the webpage is not visible clearly 

### Add ScreenShots

![Screenshot_20240930-223544](https://github.com/user-attachments/assets/1f32821c-5e71-463c-a453-39d14bfe59e8)

![Screenshot_20240930-223541](https://github.com/user-attachments/assets/d5513435-4e18-48e6-a998-6ac5ffc5018e)
The elements are collapsed upon eachother 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [ ] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by IshuSinghSE** [comment]
Hello, Could you assign me for this issue! @Harish-2003

**Comment by Harish-2003** [comment]
Make an pr
