### ISSUE TITLE
[Feature Request]: hover effect

### ISSUE THREAD

**Issue by abhi200446** [OpenTekHub/blockchain#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

add hovering at the navbar please assign @pa
![Screenshot 3](https://github.com/user-attachments/assets/a0c7e4be-ef97-48bf-b2b4-e7abf88ea40b)

### Use Case

The hover effect gives users visual feedback when they interact with the navbar, making navigation smoother.

### Benefits

Users are more likely to interact with a polished interface.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Harish-2003** [comment]
I don't think we have a navbar yet please look into the website

**Comment by rohir1132yadav** [comment]
i want to work on this issue ,please assign me.
