### ISSUE TITLE
[Bug]: missing files

### ISSUE THREAD

**Issue by priyashuu** [OpenTekHub/blockchain#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

is this a repo for contributing , i couldnt find any  index.html file 

### Add ScreenShots

![Screenshot 2024-10-02 220629](https://github.com/user-attachments/assets/e968471d-3c22-47d3-ae2f-7b4329466a75)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Harish-2003** [comment]
U need to check gh-pages branch

**Comment by priyashuu** [comment]
ok ok ,thank you
