### ISSUE TITLE
[Feature Request]: want to animations

### ISSUE THREAD

**Issue by priyashuu** [OpenTekHub/blockchain#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Objective: I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic, and use framer motion to enhance the navbar animations

Details:

Animate heading and subheading text on page load.
Include subtle fade-in or slide-in animations for improved visual appeal.
Ensure animations are responsive and do not affect performance on lower-end devices.
Will add comments to code to ensure clarity for future contributors.
Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest,wob'24

Looking forward to your feedback!

### Use Case

used gsap 
use framer motion libraries

### Benefits

it will enhanced the user-interaction

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by IshuSinghSE** [comment]
Hello I want to tweak this changes to the UI, please assign me @Harish-2003

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this.

**Comment by priyashuu** [comment]
hello sir , its complete can you check it #77
