### ISSUE TITLE
[Feature Request]: DARK THEME FUNCTIONALITY TOGGLE SWITCH

### ISSUE THREAD

**Issue by STDYGIT** [OpenTekHub/blockchain#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to implement a comprehensive dark theme for your website, recognizing the growing number of users who prefer this aesthetic for their daily tasks. I can customize the design using an appropriate color palette to enhance user experience and accessibility.
below are the switch toggle have a look

### Use Case

This feature Enhances your overallloook of the website also is a appreciatable step towards your prject
![Screenshot 2024-10-02 at 12 44 31 PM](https://github.com/user-attachments/assets/f2741457-24bd-405e-b6a4-9f915d7b1361)
![Screenshot 2024-10-02 at 12 44 47 PM](https://github.com/user-attachments/assets/5ab09dfe-1bbe-451f-945e-3231050e4db7)

### Benefits

this benifits to the user interation with styles in dark and light mode

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by STDYGIT** [comment]
Sir @Harish-2003  I would like to work on this feature and would appreciate it if you could assign it to me for Hacktoberfest and GGSOC '24. I believe this is a level 2 task, as it requires a complete overhaul of the page styles. Thank you!

**Comment by Harish-2003** [comment]
Enabling dark mode light mode?

**Comment by STDYGIT** [comment]
> Enabling dark mode light mode?

Yes I wish to add dark and light mode of your website

**Comment by IshuSinghSE** [comment]
Can I get assign for this issue @Harish-2003

**Comment by Kavish-Paraswar** [comment]
Given my strong background in HTML, CSS, and JavaScript, I would like to request this task be assigned to me as well as other assingness . I intend to mark this under the GSoC extended projects.
