### ISSUE TITLE
Add "Scroll to Top " button to the Website

### ISSUE THREAD

**Issue by rutikakengal** [OpenTekHub/blockchain#63]
Add gssoc-ext, hactoberfest accepted, level labels , Assign me i like to work on it

**Comment by Harish-2003** [comment]
U need to go to the gh-pages branch for the code

**Comment by rutikakengal** [comment]
how? Im  not understanding ,I am using github desktop

**Comment by Harish-2003** [comment]
Go and read the docs this is not the place for questions
