### ISSUE TITLE
Add license to the project

### ISSUE THREAD

**Issue by Harish-2003** [OpenTekHub/blockchain#7]

**Comment by neyhere07** [comment]
Hello Admin @Harish-2003, I'm a WOB Contributor-2024. I would like to add the License to this repository. Please assign this issue to me. Thank you!

**Comment by Harish-2003** [comment]
Make a pr

**Comment by neyhere07** [comment]
Okay sure! I have few questions to ask.
1. Which License would you like to add? Is it <strong>MIT License</strong> or anything else?
2. If <strong>MIT License</strong> is your choice, what name would you like to add in place of "Full Name?" Is it <strong>OpenTekHub</strong> or your name?

![mit license ](https://github.com/user-attachments/assets/eaf9187a-c69f-4155-b918-61a1e0b72e5b)

**Comment by Harish-2003** [comment]
Any licence related to website open sourcing you can add opentekhub

**Comment by Harish-2003** [comment]
Any licence related to website open sourcing you can add opentekhub

**Comment by neyhere07** [comment]
Okay I'll add MIT License by naming OpenTekHub.

**Comment by Harish-2003** [comment]
Reference this issue while making an pr

**Comment by neyhere07** [comment]
@Harish-2003 Raised the pull request. Please check.
