### ISSUE TITLE
Back to Top button

### ISSUE THREAD

**Issue by souvikpramanikgit** [OpenTekHub/blockchain#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

If this button is not present it causes problem for users to smoothly scroll to the top

### Use Case

A "Back to Top" button that is fixed to the bottom right corner of the page. When clicked, it smoothly scrolls the user back to the top of the page.

### Benefits

Enhance the website

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by IshaniSaikia** [comment]
can you please assigned this to me i want to work on it

**Comment by HELLSiNG76** [comment]
Hey @Harish-2003 I would love to contribute in this as my first contribution for gSSoC
