### ISSUE TITLE
Enhance the ui/ux look of the website 

### ISSUE THREAD

**Issue by Harish-2003** [OpenTekHub/blockchain#8]
you can see the website live at [opentekhub.github.io/blockchain](https://opentekhub.github.io/blockchain/) enhance the look by following the contribution guidelines

**Comment by vansh-codes** [comment]
I would like to work on this issue, please assign me

**Comment by SandhyaSankararaman** [comment]
Hi, I would like to work on this issue. Please assign it to me

**Comment by Harish-2003** [comment]
Make an pr

**Comment by IshuSinghSE** [comment]
Hello, I would like to work on this issue, assign me.

**Comment by Harish-2003** [comment]
Make an pr

**Comment by Bruhbytes** [comment]
Since this issue was not assigned to anybody, I have worked on this issue and made the PR, please review it.

**Comment by Harish-2003** [comment]
Sure will look into it
