### ISSUE TITLE
Adding All Contributors' Profile Photos

### ISSUE THREAD

**Issue by souvikpramanikgit** [OpenTekHub/blockchain#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

It lacks Contributors Profiles in Readme.md

It should be Like the image that I have shared

Hey! I have already fixed it. Can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

I will add this type of Live Contributor Profile Photos in it.
![image](https://github.com/user-attachments/assets/bfb3b922-74bb-4b52-8638-1586ccfaf7cf)

### Use Case

It showing who contributed in this project.

### Benefits

It lacks Contributors Profiles in Readme.md. So it will show who contribute in this project.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Harish-2003** [comment]
In readme file?

**Comment by souvikpramanikgit** [comment]
> In readme file?

Yes
