### ISSUE TITLE
[Feature Request]: Changing the ui/ux and colour pattern 

### ISSUE THREAD

**Issue by Aazib-at-hub** [OpenTekHub/blockchain#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

changing ui/ux and colour theme somewhere its very dull and somewhere it's just too bright and making a interactive interface.

### Use Case

It will become more readable and bright colour will not hurt the eyes.

### Benefits

this is the most visible issue in the site if it is resolved we can focus on other things too.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by Aazib-at-hub** [comment]
@sanjay-kv @KiranBaliga @Harish-2003 you have not assinged me yet i have done the work and created a pull request, Please look into the matter.

**Comment by ChauhanAyush04** [comment]
Plz assign me this

**Comment by sanjay-kv** [comment]
@Aazib-at-hub bro please don't tag me, I'm not the project admin. 

I don't have any right to assign Pr or issue in someone's repo. 

I can only manage labels related issues.

**Comment by Aazib-at-hub** [comment]
@Harish-2003 @KiranBaliga  you have not assinged me yet i have done the work and created a pull request, Please look into the matter.
